# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a043d6d8660137d27e30f0319dbee24cbdc474b7621f84d49d4027b8164fb3ea1380dedf00dfa36b672946d021bc96772b2ef8e0dd106c871fe545798281f216
  MANDRILL_APIKEY: pWRoI8bd9LO7YZ5aW7FJAA
  MANDRILL_USERNAME: austen.lane.roberts@gmail.com
test:
  secret_key_base: 08b742d6c86557208b1ebd44bd8a32c62aca0da4d2d20106a8f90b1822f928d9063c1c64cd8d0d8c4e216bf01b5ccaacb425721be9373337438ac8b54725a421
  MANDRILL_APIKEY: pWRoI8bd9LO7YZ5aW7FJAA
  MANDRILL_USERNAME: austen.lane.roberts@gmail.com
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
